// <auto-generated />
namespace EmergAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updateDateUserOperatorToString : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateDateUserOperatorToString));
        
        string IMigrationMetadata.Id
        {
            get { return "201805241322176_updateDateUserOperatorToString"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
